#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
include dracula.conf
symbol_map U+4E00-U+9FFF Sarasa Mono SC
font_family	Cascadia Code
bold_font	Cascadia Code
italic_font	Cascadia Code
bold_italic_font	Cascadia Code
font_size                   14
remember_window_size        no
initial_window_width        1000
initial_window_height       650
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        5
#hide_window_decorations     yes
background_opacity          0.8
#background_opacity          1
background_blur             75
dynamic_background_opacity  yes
confirm_os_window_close     0
selection_foreground        none
selection_background        none
cursor_trail 1
env XMODIFIERS=@im=fcitx5  # 传递输入法环境变量
env GLFW_IM_MODULE=fcitx5
# Include Custom Configuration
allow_remote_control yes
listen_on unix:/tmp/kitty
# scrollback_pager kqe +INPUT_LINE_NUMBER
scrollback_pager kqe --input-line INPUT_LINE_NUMBER  --cursor-line CURSOR_LINE  --cursor-column CURSOR_COLUMN
map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
#enable_ime yes
clipboard_control write-clipboard read-clipboard
map ctrl+shift+g send_text all \x03
map ctrl+shift+t launch --location=hsplit
map ctrl+shift+v launch --location=vsplit
map ctrl+shift+n next_window
map ctrl+shift+p previous_window
map ctrl+shift+d close_window
map ctrl+shift+k show_scrollback
# map ctrl+shift+k combine : send_text application \x0c : show_scrollback
# 结合两个动作：发送清屏信号，然后打开滚动历史查看器
# map ctrl+shift+k combine : send_text normal,application \x0c : show_scrollback
enabled_layouts splits