#!/usr/bin/env bash
pkill xwayland-satellite
sleep 1
xwayland-satellite &

SCREEN="eDP-1"

if niri msg outputs | grep -A2 "DP-2"; then

if niri msg outputs | grep -A2 "$SCREEN" | grep -q "Disabled"; then
    niri msg output "$SCREEN" on
else
    niri msg output "$SCREEN" off
fi

fi
